name: compile-with-ndk
on:
  push:
    paths:
     - sample.c
  workflow_dispatch:
jobs:
  autoreconf:
    uses: turistu/odds-n-ends/.github/workflows/auto.yml@main
    permissions:
      contents: write
  compile:
    needs: autoreconf
    uses: turistu/odds-n-ends/.github/workflows/build-with-ndk.yml
    with:
      ref: ${{github.ref_name}}-auto
