name: build with Android NDK
on:
  push:
    paths:
     - sample.c
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: ./util
        with: ndk x86_64 21 cc sample.c -o sample
