name: compile-with-ndk
on:
  push:
    paths:
     - sample.c
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./util
        with:
          cmd: ndk x86_64 21 cc sample.c -o sample
